name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install just
      uses: extractions/setup-just@v1
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake ninja-build

    - name: Build and Test
      run: |
        just build
        just test
