name: C++ Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install just
      uses: extractions/setup-just@v1

    - name: Clone vcpkg
      if: !exists('vcpkg')
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake ninja-build make

    - name: Build and Test
      run: |
        just build
        just test
      env:
        CMAKE_TOOLCHAIN_FILE: "${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
